name: minimalkv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
# Store SDKs
  # Cloud
  - azure-storage-blob
  - boto
  - boto3
  - gcsfs
  # DB
  - redis-py
  - psycopg2
  - sqlalchemy
  - pymongo
  - pymysql
  # Git
  - dulwich
# Utils
  - uritools
  - six
# Testing
  - mock
  - pytest
  - pytest-mock
  - pytest-xdist
  - pytest-cov
# Infrastructure
  - pre-commit
  - setuptools-scm
  - sphinx
  - docker-compose