name: minimalkv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - azure-storage-blob
  - boto
  - boto3
  - dulwich
  - fsspec
  - gcsfs>=2022.10.0
  - s3fs>=2022.10.0
  - mock
  - pip
  - pre-commit
  - psycopg2
  - pyarrow
  - python-build
  - pymongo
  - pymysql
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-xdist  
  - python
  - redis-py
  - setuptools-scm
  - six
  - sphinx  
  - sqlalchemy
  - uritools
  # type checking dependencies
  - mypy>=1.6.1
  - types-mock
  - types-setuptools
  - types-redis
  - types-boto
  - boto3-stubs
